# Praca Domowa

In [3]:
import numpy as np
import pandas as pd

Zad 1

In [4]:
np.genfromtxt('Zadanie_1.csv', delimiter=';')  # bez konwertowania
# to samo co read csv i potem to numpy arr

array([[         nan,          nan,          nan,          nan,
                 nan,          nan,          nan,          nan,
                 nan,          nan,          nan,          nan,
                 nan,          nan,          nan,          nan],
       [3.600000e+01, 2.700000e+01, 7.100000e+01, 8.100000e+00,
        3.340000e+00, 1.140000e+01, 8.150000e+01, 3.243000e+03,
        8.800000e+00, 4.260000e+01, 1.170000e+01, 2.100000e+01,
                 nan, 5.900000e+01, 5.900000e+01, 9.218700e+02],
       [3.500000e+01, 2.300000e+01, 7.200000e+01, 1.110000e+01,
        3.140000e+00, 1.100000e+01, 7.880000e+01, 4.281000e+03,
        3.600000e+00, 5.070000e+01, 1.440000e+01, 8.000000e+00,
        1.000000e+01, 3.900000e+01, 5.700000e+01, 9.978750e+02],
       [4.400000e+01, 2.900000e+01, 7.400000e+01, 1.040000e+01,
        3.210000e+00, 9.800000e+00, 8.160000e+01, 4.260000e+03,
        8.000000e-01, 3.940000e+01,          nan, 6.000000e+00,
        6.000000e+00, 3.300000e+01, 5

In [5]:
z1nparr = np.genfromtxt('Zadanie_1.csv', delimiter=';', skip_header=True)
z1nparr

array([[3.600000e+01, 2.700000e+01, 7.100000e+01, 8.100000e+00,
        3.340000e+00, 1.140000e+01, 8.150000e+01, 3.243000e+03,
        8.800000e+00, 4.260000e+01, 1.170000e+01, 2.100000e+01,
                 nan, 5.900000e+01, 5.900000e+01, 9.218700e+02],
       [3.500000e+01, 2.300000e+01, 7.200000e+01, 1.110000e+01,
        3.140000e+00, 1.100000e+01, 7.880000e+01, 4.281000e+03,
        3.600000e+00, 5.070000e+01, 1.440000e+01, 8.000000e+00,
        1.000000e+01, 3.900000e+01, 5.700000e+01, 9.978750e+02],
       [4.400000e+01, 2.900000e+01, 7.400000e+01, 1.040000e+01,
        3.210000e+00, 9.800000e+00, 8.160000e+01, 4.260000e+03,
        8.000000e-01, 3.940000e+01,          nan, 6.000000e+00,
        6.000000e+00, 3.300000e+01, 5.400000e+01, 9.623540e+02],
       [4.700000e+01, 4.500000e+01, 7.900000e+01, 6.500000e+00,
        3.410000e+00, 1.110000e+01, 7.750000e+01, 3.125000e+03,
        2.710000e+01, 5.020000e+01, 2.060000e+01, 1.800000e+01,
        8.000000e+00, 2.400000e+01, 5

In [6]:
# zad1 a
cell_count = z1nparr.size
print(f'cell_count={cell_count}')

cell_count=960


In [7]:
# zad1 b
row_count = z1nparr.shape[0]
col_count = z1nparr.shape[1]
print(f'row_count={row_count}, col_count={col_count}')

row_count=60, col_count=16


In [8]:
# zad1 c
mean = np.nanmean(z1nparr)
med = np.nanmedian(z1nparr)
var = np.nanvar(z1nparr)
print(f'mean={mean}, med={med}, var={var}')

mean=338.22093191489364, med=33.4, var=1036473.5935947594


In [9]:
# zad1 d
z1nparr = z1nparr[~np.isnan(z1nparr)]
z1nparr

array([3.600000e+01, 2.700000e+01, 7.100000e+01, 8.100000e+00,
       3.340000e+00, 1.140000e+01, 8.150000e+01, 3.243000e+03,
       8.800000e+00, 4.260000e+01, 1.170000e+01, 2.100000e+01,
       5.900000e+01, 5.900000e+01, 9.218700e+02, 3.500000e+01,
       2.300000e+01, 7.200000e+01, 1.110000e+01, 3.140000e+00,
       1.100000e+01, 7.880000e+01, 4.281000e+03, 3.600000e+00,
       5.070000e+01, 1.440000e+01, 8.000000e+00, 1.000000e+01,
       3.900000e+01, 5.700000e+01, 9.978750e+02, 4.400000e+01,
       2.900000e+01, 7.400000e+01, 1.040000e+01, 3.210000e+00,
       9.800000e+00, 8.160000e+01, 4.260000e+03, 8.000000e-01,
       3.940000e+01, 6.000000e+00, 6.000000e+00, 3.300000e+01,
       5.400000e+01, 9.623540e+02, 4.700000e+01, 4.500000e+01,
       7.900000e+01, 6.500000e+00, 3.410000e+00, 1.110000e+01,
       7.750000e+01, 3.125000e+03, 2.710000e+01, 5.020000e+01,
       2.060000e+01, 1.800000e+01, 8.000000e+00, 2.400000e+01,
       5.600000e+01, 9.822910e+02, 4.300000e+01, 3.5000

In [10]:
np.isnan(z1nparr).any()

False

In [11]:
mean = np.mean(z1nparr)
med = np.median(z1nparr)
var = np.var(z1nparr)
print(f'mean={mean}, med={med}, var={var}')

mean=338.2209319148936, med=33.4, var=1036473.5935947594


Zad 2

In [12]:
# zad2 a
z2nparr = np.genfromtxt('Zadanie_2.csv', delimiter=';')
z2nparr

array([[  1.,   2.,  15., -59.,   9.,   3.,  75.,   6.,   7.,   1.],
       [  0.,   5.,   0.,   4.,   6.,  16.,  44.,   7.,   1.,   1.],
       [  7.,  14.,   3., -10.,   9.,  15.,  73.,   8.,   2.,   9.],
       [  1.,   5.,  15., -54.,   5.,  15.,  35.,   8.,   6.,   4.],
       [  0.,   8.,   5., -18.,   7.,  16.,  91.,   6.,   7.,   9.],
       [  7.,  18.,  23., -90.,   4.,   8.,  31.,   0.,   1.,   7.],
       [  2.,   8.,  20., -72.,   4.,   1.,  91.,   9.,   4.,   4.],
       [  4.,  12.,  18., -65.,   6.,   9.,  76.,   4.,   9.,   9.],
       [  7.,  15.,  13., -52.,   5.,   7.,  54.,   2.,   7.,   0.],
       [  2.,   9.,  15., -56.,   6.,   1.,  98.,   4.,   8.,   4.]])

In [13]:
z2nparr.shape

(10, 10)

In [14]:
EIG = np.linalg.eig(z2nparr)
EIG

(array([104.34960192 +0.j        , -23.35660516+18.84992811j,
        -23.35660516-18.84992811j,  15.92989017 +0.j        ,
         -4.99456452 +0.j        ,   0.35205717 +5.80125175j,
          0.35205717 -5.80125175j,  -1.03383491 +0.j        ,
          3.87900166 +1.42651533j,   3.87900166 -1.42651533j]),
 array([[-0.29000475+0.j        , -0.07545445+0.07743149j,
         -0.07545445-0.07743149j, -0.03544485+0.j        ,
          0.42681634+0.j        , -0.22172831-0.29869259j,
         -0.22172831+0.29869259j,  0.41343726+0.j        ,
         -0.28670255+0.21891569j, -0.28670255-0.21891569j],
        [-0.24163153+0.j        ,  0.41229621+0.09197324j,
          0.41229621-0.09197324j,  0.45873475+0.j        ,
         -0.27056206+0.j        , -0.01331344+0.1422557j ,
         -0.01331344-0.1422557j , -0.31591047+0.j        ,
          0.41954481-0.10561864j,  0.41954481+0.10561864j],
        [-0.41060573+0.j        ,  0.37509638-0.00960818j,
          0.37509638+0.00960818j,  0.

In [15]:
# zad2 b
inv = np.linalg.inv(z2nparr)
inv

array([[ 0.47461371,  0.13269253, -0.24726695, -0.82965177,  0.28250384,
        -0.17012825,  0.58274426,  0.83686705,  0.4146721 , -1.56942847],
       [-0.38032531, -0.11226789,  0.23216372,  0.58853747, -0.2508954 ,
         0.10174485, -0.40729564, -0.58325689, -0.2335154 ,  1.11832726],
       [ 0.13559662,  0.58950334, -0.24709855, -0.58789838, -0.30170699,
        -0.12721938,  0.23740295,  1.01003036, -0.02151387, -0.64590149],
       [ 0.01425207,  0.14570726, -0.04557569, -0.12721972, -0.08945184,
        -0.03756624,  0.03910376,  0.23606066, -0.01436771, -0.11345749],
       [-0.09473246,  0.01725249,  0.19145597,  0.32960274, -0.28626296,
         0.08348529, -0.37577603, -0.27295934, -0.25855803,  0.74691827],
       [ 0.16387032,  0.10075684, -0.15404907, -0.29794662,  0.16916877,
        -0.02827782,  0.20469921,  0.28036265,  0.15086178, -0.5882585 ],
       [ 0.04288003,  0.02246462, -0.0366803 , -0.09024915,  0.04322146,
        -0.01047861,  0.06167348,  0.07009721

Zad 3

In [16]:
# zad3
A = np.genfromtxt('Zadanie_3_macierz_A.csv', delimiter=',')
A

array([[2., 2., 3.],
       [1., 0., 4.],
       [6., 9., 7.]])

In [17]:
B = np.genfromtxt('Zadanie_3_macierz_B.csv', delimiter=',')
print(B)
print(B.T)

[[ 1.  5.  2.]
 [ 6.  6.  4.]
 [ 1. 10.  7.]
 [ 5.  8.  2.]
 [ 3.  0.  6.]]
[[ 1.  6.  1.  5.  3.]
 [ 5.  6. 10.  8.  0.]
 [ 2.  4.  7.  2.  6.]]


In [18]:
dividend = np.dot(A, B.T)
dividend

array([[ 18.,  36.,  43.,  32.,  24.],
       [  9.,  22.,  29.,  13.,  27.],
       [ 65., 118., 145., 116.,  60.]])

In [19]:
divider1 = np.sqrt(np.sum(A**2, axis=1))
divider2 = np.sqrt(np.sum(B**2, axis=1))
divider1, divider2

(array([ 4.12310563,  4.12310563, 12.88409873]),
 array([ 5.47722558,  9.38083152, 12.24744871,  9.64365076,  6.70820393]))

In [20]:
divider1 = np.sqrt(np.sum(A**2, axis=1))[:, np.newaxis]
divider2 = np.sqrt(np.sum(B**2, axis=1))[np.newaxis, :]
dividend/(divider1*divider2)

array([[0.7970534 , 0.93075784, 0.85152689, 0.80479273, 0.86772183],
       [0.3985267 , 0.56879646, 0.57428557, 0.32694705, 0.97618706],
       [0.92108283, 0.9763075 , 0.91890016, 0.9336035 , 0.69421013]])

Zad 4

In [21]:
zad4 = pd.read_csv('Zadanie_4.csv', sep=';')
zad4

DateTime  DoctorID Type    City  Unnamed: 4  Unnamed: 5  \
0    16.03.2020 12:00         1   GP  Warsaw         NaN         NaN   
1    16.03.2020 12:01         1   GP  Warsaw         NaN         NaN   
2    16.03.2020 12:02         1   GP  Warsaw         NaN         NaN   
3    16.03.2020 12:03         1   GP  Warsaw         NaN         NaN   
4    16.03.2020 12:04         1   GP  Warsaw         NaN         NaN   
..                ...       ...  ...     ...         ...         ...   
194  29.03.2020 14:33         1   GP  Warsaw         NaN         NaN   
195  29.03.2020 14:34         1   GP  Warsaw         NaN         NaN   
196  29.03.2020 14:35         1   GP  Warsaw         NaN         NaN   
197  29.03.2020 14:36         1   GP  Warsaw         NaN         NaN   
198  29.03.2020 14:37         1   GP  Warsaw         NaN         NaN   

     Unnamed: 6  Unnamed: 7  
0           NaN         NaN  
1           NaN         NaN  
2           NaN         NaN  
3           NaN         NaN  
4           NaN         NaN  
..          ...         ...  
194         NaN         NaN  
195         NaN         NaN  
196         NaN         NaN  
197         NaN         NaN  
198         NaN         NaN  

[199 rows x 8 columns]

In [22]:
zad4 = zad4.loc[:, ~zad4.columns.str.contains('^Unnamed')]
zad4

DateTime  DoctorID Type    City
0    16.03.2020 12:00         1   GP  Warsaw
1    16.03.2020 12:01         1   GP  Warsaw
2    16.03.2020 12:02         1   GP  Warsaw
3    16.03.2020 12:03         1   GP  Warsaw
4    16.03.2020 12:04         1   GP  Warsaw
..                ...       ...  ...     ...
194  29.03.2020 14:33         1   GP  Warsaw
195  29.03.2020 14:34         1   GP  Warsaw
196  29.03.2020 14:35         1   GP  Warsaw
197  29.03.2020 14:36         1   GP  Warsaw
198  29.03.2020 14:37         1   GP  Warsaw

[199 rows x 4 columns]

In [23]:
zad4['Date'] = pd.to_datetime(zad4['DateTime']).dt.date
zad4['Time'] = pd.to_datetime(zad4['DateTime']).dt.time
zad4

/tmp/ipykernel_3160/4137987454.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  zad4['Date'] = pd.to_datetime(zad4['DateTime']).dt.date
/tmp/ipykernel_3160/4137987454.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  zad4['Time'] = pd.to_datetime(zad4['DateTime']).dt.time


DateTime  DoctorID Type    City        Date      Time
0    16.03.2020 12:00         1   GP  Warsaw  2020-03-16  12:00:00
1    16.03.2020 12:01         1   GP  Warsaw  2020-03-16  12:01:00
2    16.03.2020 12:02         1   GP  Warsaw  2020-03-16  12:02:00
3    16.03.2020 12:03         1   GP  Warsaw  2020-03-16  12:03:00
4    16.03.2020 12:04         1   GP  Warsaw  2020-03-16  12:04:00
..                ...       ...  ...     ...         ...       ...
194  29.03.2020 14:33         1   GP  Warsaw  2020-03-29  14:33:00
195  29.03.2020 14:34         1   GP  Warsaw  2020-03-29  14:34:00
196  29.03.2020 14:35         1   GP  Warsaw  2020-03-29  14:35:00
197  29.03.2020 14:36         1   GP  Warsaw  2020-03-29  14:36:00
198  29.03.2020 14:37         1   GP  Warsaw  2020-03-29  14:37:00

[199 rows x 6 columns]

In [24]:
zad4.drop(labels='DateTime', inplace=True, axis=1)
zad4

/home/s26549/anaconda3/lib/python3.9/site-packages/pandas/core/frame.py:4906: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


DoctorID Type    City        Date      Time
0           1   GP  Warsaw  2020-03-16  12:00:00
1           1   GP  Warsaw  2020-03-16  12:01:00
2           1   GP  Warsaw  2020-03-16  12:02:00
3           1   GP  Warsaw  2020-03-16  12:03:00
4           1   GP  Warsaw  2020-03-16  12:04:00
..        ...  ...     ...         ...       ...
194         1   GP  Warsaw  2020-03-29  14:33:00
195         1   GP  Warsaw  2020-03-29  14:34:00
196         1   GP  Warsaw  2020-03-29  14:35:00
197         1   GP  Warsaw  2020-03-29  14:36:00
198         1   GP  Warsaw  2020-03-29  14:37:00

[199 rows x 5 columns]

In [25]:
df1 = zad4.groupby(['Date', 'City', 'DoctorID', 'Type']).min()
df1.reset_index()
df1

Time
Date       City   DoctorID Type                   
2020-03-16 Krakow 2        GP             12:00:00
           Warsaw 1        GP             12:00:00
2020-03-22 Warsaw 3        Sugreon        08:01:00
2020-03-29 Warsaw 1        GP             14:00:00
2020-10-04 Krakow 4        Opthomologist  13:20:00

In [26]:
df2 = zad4.groupby(['Date', 'City', 'DoctorID', 'Type']).max()
df2.reset_index()
df2

Time
Date       City   DoctorID Type                   
2020-03-16 Krakow 2        GP             12:49:00
           Warsaw 1        GP             14:01:00
2020-03-22 Warsaw 3        Sugreon        09:06:00
2020-03-29 Warsaw 1        GP             14:37:00
2020-10-04 Krakow 4        Opthomologist  13:34:00

In [27]:
df3 = pd.merge(df1, df2, how='inner', on=['Date', 'City', 'DoctorID', 'Type'])
df3

Time_x    Time_y
Date       City   DoctorID Type                             
2020-03-16 Krakow 2        GP             12:00:00  12:49:00
           Warsaw 1        GP             12:00:00  14:01:00
2020-03-22 Warsaw 3        Sugreon        08:01:00  09:06:00
2020-03-29 Warsaw 1        GP             14:00:00  14:37:00
2020-10-04 Krakow 4        Opthomologist  13:20:00  13:34:00

In [28]:
df3.rename(columns={'Time_x':'From', 'Time_y':'To'}, inplace=True)
df3.reset_index()
df3

From        To
Date       City   DoctorID Type                             
2020-03-16 Krakow 2        GP             12:00:00  12:49:00
           Warsaw 1        GP             12:00:00  14:01:00
2020-03-22 Warsaw 3        Sugreon        08:01:00  09:06:00
2020-03-29 Warsaw 1        GP             14:00:00  14:37:00
2020-10-04 Krakow 4        Opthomologist  13:20:00  13:34:00

In [29]:
df3.to_csv('doc_availability.csv', sep=';')